rm is-stream
sindresorhus/execa pull request #520
Opened 2023-02-20 01:15 UTC by jimmywarting

sprinkled little optional chaining into it

2023-02-20 02:09 UTC, ehmicky commented
Hi @jimmywarting,

Thanks a lot for your contribution!

I do not have a strong opinion either for or against inlining `is-stream`. However, I believe @sindresorhus has had some concerns about such inlining PRs in the past, so I'd be curious to know what he thinks.

2023-02-28 06:10 UTC, sindresorhus requested changes

2023-02-28 06:10 UTC, sindresorhus commented on lib/stream.js
> +	if (typeof input?.pipe === 'function') {
For readability, make a `isStream` method.

2023-02-28 06:10 UTC, sindresorhus commented on lib/stream.js
> +	input?.pipe?.(spawned.stdin) || spawned.stdin.end(input);
This is not an improvement.

2023-02-28 06:11 UTC, sindresorhus commented
I'm ok with removing it. The PR needs a better title though.

2023-06-20 12:01 UTC, sindresorhus commented
Closing for lack of response.

2023-06-20 12:01 UTC, closed without merging